export const ADMIN_ROUTE = '/admin'
export const STORE_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const GAME_ROUTE = '/game'
export const ABOUT_ROUTE = '/about'